# Site settings
title: qIIq, an Equilibrium Investments Private Limited venture
email: admin@qiiq.co.in
description: > # this means to ignore newlines until "baseurl:"
  Explore technology to make our lives simpler. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  aantony
# Build settings
markdown: kramdown
